version: '3.3'
services:
  viz:
    image: hypriot/visualizer:linux-arm64
    ports:
     - 8000:8080
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
      labels:
        raefik.http.routers.viz.entrypoints: web
        traefik.docker.network: traefik_net
        traefik.enable: 'true'
        traefik.http.routers.viz.rule: Host(`viz.swarm`)
        traefik.http.routers.viz.service: viz
        traefik.http.services.viz.loadbalancer.server.port: '8080'

networks:
  traefik_net:
    external: true
