version: '3.3'
services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    environment:
      PGID: '1000'
      PUID: '1000'
    ports:
     - 3478:3478/udp
     - 10001:10001/udp
     - 8080:8080
     - 8443:8443
     - 1900:1900/udp
     - 8843:8843
     - 8880:8880
     - 6789:6789
     - 5514:5514
    volumes:
     - unifi_config:/config
    networks:
     - traefik_net
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.docker.network: traefik_net
        traefik.enable: 'true'
        traefik.http.routers.unifi-controller.entrypoints: web
        traefik.http.routers.unifi-controller.rule: Host(`unifi.local.swarm`)
        traefik.http.routers.unifi-controller.service: unifi-controller
        traefik.http.services.unifi-controller.loadbalancer.server.port: '8443'
networks:
  traefik_net:
    external: true
volumes:
  unifi_config:
    external: true
